In [1]:
import torch

In [2]:
torch.__version__

'1.5.1'

In [3]:
import numpy as np

In [4]:
lst = [1,3,4,5,7]
arr = np.array(lst)

In [5]:
arr

array([1, 3, 4, 5, 7])

In [6]:
tensors = torch.from_numpy(arr)
tensors


tensor([1, 3, 4, 5, 7], dtype=torch.int32)

In [7]:
tensors[1:4]

tensor([3, 4, 5], dtype=torch.int32)

In [8]:
tensors[:2]

tensor([1, 3], dtype=torch.int32)

In [9]:
tensors[3]=100
tensors

tensor([  1,   3,   4, 100,   7], dtype=torch.int32)

In [11]:
arr #shares same memory so array also changes

array([  1,   3,   4, 100,   7])

In [16]:
tensor_copy = torch.tensor(arr)
tensor_copy[3]=21 #solution

In [14]:
tensor_copy

tensor([ 1,  3,  4, 21,  7], dtype=torch.int32)

In [15]:
arr

array([  1,   3,   4, 100,   7])

In [18]:
torch.zeros(2,3,dtype=torch.float64)

tensor([[0., 0., 0.],
        [0., 0., 0.]], dtype=torch.float64)

In [19]:
torch.ones(3,2,dtype=torch.int16)

tensor([[1, 1],
        [1, 1],
        [1, 1]], dtype=torch.int16)

In [20]:
a= torch.tensor([2,3,4])
b= torch.tensor([5,6,7])
a+b

tensor([ 7,  9, 11])

In [26]:
torch.add(a,b)

tensor([ 7,  9, 11])

In [23]:
x=torch.tensor(np.arange(0,15).reshape(5,3))

In [24]:
x

tensor([[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11],
        [12, 13, 14]], dtype=torch.int32)

In [25]:
x[:,0]

tensor([ 0,  3,  6,  9, 12], dtype=torch.int32)

In [27]:
c=torch.zeros(a.shape)

In [28]:
c

tensor([0., 0., 0.])

In [29]:
torch.add(a,b,out=c)

tensor([ 7.,  9., 11.])

In [30]:
c

tensor([ 7.,  9., 11.])

In [31]:
torch.add(a,b).sum()

tensor(27)

In [33]:
torch.sum(c)

tensor(27.)

In [34]:
x= torch.tensor([2,3,4])
y= torch.tensor([5,6,7])


In [35]:
x.mul(y)

tensor([10, 18, 28])

In [37]:
x.mul(y).sum()

tensor(56)

In [36]:
x.dot(y)

tensor(56)

In [39]:
x= torch.tensor([[2,3,4],[3,4,5]])
y= torch.tensor([[5,6],[3,4],[6,7]])

In [40]:
x@y

tensor([[43, 52],
        [57, 69]])

In [41]:
torch.mm(x,y)

tensor([[43, 52],
        [57, 69]])

In [42]:
torch.matmul(x,y)

tensor([[43, 52],
        [57, 69]])