In [1]:
import torch

In [2]:
x =  torch.tensor(4.0,requires_grad=True)

In [3]:
x

tensor(4., requires_grad=True)

In [4]:
y=x**2

In [5]:
y

tensor(16., grad_fn=<PowBackward0>)

In [6]:
## bak propagation => y =2*x
y.backward()

In [7]:
y

tensor(16., grad_fn=<PowBackward0>)

In [8]:
print(x.grad)

tensor(8.)


In [13]:
torch_inp = torch.tensor([[2,3,1],[3,4,5],[8,7,2]],dtype=torch.float64,requires_grad=True)

In [14]:
torch_inp

tensor([[2., 3., 1.],
        [3., 4., 5.],
        [8., 7., 2.]], dtype=torch.float64, requires_grad=True)

In [15]:
y = torch_inp**3 + torch_inp**2
y

tensor([[ 12.,  36.,   2.],
        [ 36.,  80., 150.],
        [576., 392.,  12.]], dtype=torch.float64, grad_fn=<AddBackward0>)

In [17]:
z = y.sum()
z

tensor(1296., dtype=torch.float64, grad_fn=<SumBackward0>)

In [18]:
z.backward()

In [22]:
## 3x**2 + 2x

In [21]:
torch_inp.grad

tensor([[ 16.,  33.,   5.],
        [ 33.,  56.,  85.],
        [208., 161.,  16.]], dtype=torch.float64)